### ISSUE TITLE
Mengunggah Kode Sumber yang Belum di Build, Menambahkan Deskripsi Repositori dan Menambah Tautan Demo Aplikasi

### ISSUE THREAD

**Issue by jefrydco** [hudadamar21/code-highlighter#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Huda. Mas juga sudah menambahkan beberapa gaya sendiri. Selain itu Mas juga sudah menggunakan Vue Router. Keren Mas!

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni

1. Menambahkan Tautan ke Demo Aplikasi
Menambahkan tautan ke demo aplikasi. Untuk yang menambahkan tautan ke demo aplikasi, kalau ngga salah bisa melalui bagian yang ada di sini Mas

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96429667-673ee180-122b-11eb-957f-d26e39401f68.png)

Tautan ke demo aplikasi akan sangat berguna bagi teman-teman yang ingin melihat hasil proyek Mas ini tanpa harus menjalankannya di lokal.

2. Mengunggah Kode Sumber yang Belum di Build
Sepertinya kode yang Mas unggah ke repositori ini merupakan hasil buildnya. Kalau boleh minta tolong sekalian diunggah kode sumber yang belum di_build_ juga Mas, supaya bisa dipelajari juga bagaimana Mas membuat aplikasinya. Mungkin bisa Mas letakkan di _branch_ yang berbeda.

3. Menambahkan Deskripsi Repositori
Menurut saya akan lebih baik jika terdapat deskripsi repositori. Mas bisa menambahkan berkas bernama `readme.md` di _root_ proyek ini. Nanti secara otomatis GitHub akan menampilkan deskripsi dari berkas tersebut.

Semangat selalu ya! :muscle:

**Comment by hudadamar21** [comment]
yang belum di build sudah di unggah kok mas ada di branch master. dan yg di build ada di branch gh-pages untuk demo aplikasi nya

**Comment by jefrydco** [comment]
Ah iya maaf Mas tak kira belum diunggah, mungkin dari GitHub nya bisa diatur supaya _default branch_ nya mengarah ke master. :smile: Kalau gitu mungkin tinggal Mas tambahkan tautan ke demo aplikasinya ajah yak. Nanti kalau sudah, Mas bisa menutup _issue_ ini. Semangat ya! :muscle:
